In [1]:
%load_ext autoreload
%autoreload 2

In [ ]:
from mytokenizer import Tokenizer
import jax

tokenizer = Tokenizer("./checkpoints")

audio = jax.numpy.array(
    [
        1,
        6090,
        470,
        307,
        4193,
        783,
        553,
        5894,
        306,
        24998,
        26541,
        406,
        37520,
        13,
        50256,
    ]
)

z_q = tokenizer.vqvae.quantizer.codebook.T[audio]

# Straight-through estimator
z_q = jax.numpy.permute_dims(z_q, (1, 0))

output = tokenizer.vqvae.decoder(z_q)
print(output)

[[0.65751994 0.70697993 0.7114024  0.44222426]
 [0.73608494 0.76183087 0.7667745  0.4881196 ]
 [0.95654345 0.9757084  0.9700024  0.55742633]
 [1.3812428  1.4314709  1.4064077  0.73166764]
 [1.9839426  2.0474987  1.9697965  0.95297056]
 [2.4994745  2.62317    2.5206642  1.1871212 ]
 [3.1645105  3.3424819  3.1636393  1.3667222 ]
 [2.8477025  3.018959   2.8003316  1.1848493 ]
 [2.3993754  2.513414   2.2998543  0.96640813]
 [2.4834154  2.59261    2.3415592  0.93840736]
 [2.356126   2.4379032  2.169697   0.8609618 ]
 [2.3539047  2.4059591  2.118901   0.8687748 ]
 [2.3068979  2.3552036  2.067455   0.8615322 ]
 [2.1944537  2.2292907  1.9479003  0.84921217]
 [2.0550427  2.0754156  1.8083568  0.77973986]
 [2.0208757  2.0081434  1.7488062  0.75591403]
 [1.8440012  1.8416494  1.6083957  0.7254593 ]
 [1.7231171  1.7255569  1.5186278  0.689501  ]
 [1.5578169  1.5628048  1.3733047  0.6316358 ]
 [1.4327775  1.4368986  1.282575   0.6273489 ]
 [1.3631334  1.3651037  1.22791    0.655042  ]
 [1.3322792  

In [ ]:
import torch, numpy

print(output.shape)


tokenizer.mel_to_dvae_wav(torch.from_numpy(numpy.array(output)))

(80, 4)


RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [1, 513] but got: [1, 80].

In [ ]:
tokenizer.dvae_wav_to_mel(test).shape

torch.Size([1, 80, 87])

In [ ]:
import torch
import torchaudio
import IPython
import torch.nn as nn
import numpy as np

waveform, sample_rate = torchaudio.load("record.wav", normalize=True)

print(sample_rate)
transofrm = torchaudio.transforms.MelSpectrogram(n_fft=1024)


invers = torchaudio.transforms.InverseMelScale(n_stft=1024 // 2 + 1)
# torchaudio.transforms.GriffinLim(n_fft=n_fft, hop_length=hop_length),
# waveform = inverse_transform(torch.squeeze(features))
# return torch.unsqueeze(waveform, 0)

mel = transofrm(waveform)
unmel = invers(mel)

44100


/Users/tugdual/miniconda3/envs/xtts/lib/python3.10/site-packages/torchaudio/functional/functional.py:584: UserWarning: At least one mel filterbank has all zero values. The value for `n_mels` (128) may be set too high. Or, the value for `n_freqs` (513) may be set too low.
  warnings.warn(


_LinAlgError: torch.linalg.lstsq: The least squares solution could not be computed because the input matrix does not have full rank (error code: 1).